services:
  rest-api:
    build:
      context: /Knie_Schwarz_project_WS2024_DMS
      dockerfile: Dockerfile
    volumes:
      - data:/data
    ports:
      - "127.0.0.1:8081:8080"
    

volumes:
  data:
    driver: local