services:
  asp_rest_api:
    image: asp_rest_api_image
    build:
      context: . # Ensure this points to the correct directory where the Dockerfile is located
      dockerfile: ./ASP_Rest_API/Dockerfile     # This should match the Dockerfile name directly
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    depends_on:
      - mydocdal

  webui:
    image: web_ui_image
    build:
      context: ./WebUI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./WebUI/nginx.conf:/etc/nginx/nginx.conf
      - ./WebUI/wwwroot:/app/wwwroot
    depends_on:
      - asp_rest_api

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mydocdal:
    image: mydocdal_image
    build:
      context: .
      dockerfile: ./MyDocDAL/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db

volumes:
  postgres_data: 
